### ISSUE TITLE
uploader

### ISSUE THREAD

**Issue by aleksander-git** [aleksander-git/telegram-torrent#3]
подготовить код загрузки в телеграм, использовать https://github.com/gotd/td

код поместить в /internal/uploader

**Comment by dadilll** [comment]
У меня есть наработки на счет загрузчика. Там написан клент который отсылает видео в телеграм бота. https://github.com/dadilll/telegramupload

**Comment by dadilll** [comment]
Я пока не могу заняться разработкой из за того что я щас не дома.

**Comment by AleksandrVishniakov** [comment]
PR: https://github.com/aleksander-git/telegram-torrent/pull/5

**Comment by AleksandrVishniakov** [comment]
PR: https://github.com/aleksander-git/telegram-torrent/pull/5
